[package]
name = "lolrush"
authors = ["Harish <github.com/harish3124>"]
version = "0.4.0"
edition = "2018"

[dependencies]
colored = "2"
colorgrad = "0.5.0"
clap = "2"
rand = "0.8"
unicode-segmentation = "1.8.0"
